modLoader="javafml"
loaderVersion="[31,)"
authors="JellySquid, Jackson"
credits="JellySquid for creating Sodium."

[[mods]]
    modId="sodium"
    version="0.1.0"
    displayName="Sodium (Forge)"
    description='''Sodium is an free and open-source optimization mod for Minecraft which improves frame rates and reduces lag spikes.'''

[[dependencies.nether_extension]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.75,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nether_extension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"

