modLoader="javafml"
loaderVersion="[31,)"
authors="JellySquid"
credits="Ported by Jackson"

[[mods]]
    modId="sodium"
    version="0.1.0"
    displayName="Sodium (Forge)"
    description='''Sodium is an free and open-source optimization mod for Minecraft which improves frame rates and reduces lag spikes.'''

[[dependencies.sodium]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.75,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sodium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"

